### ISSUE TITLE
Chrome become very slow when several large images attached

### ISSUE THREAD

**Issue by marilawang** [paginagmbh/redmine_lightbox2#15] opened 2015-10-14 05:30 UTC
Upload some 5000 x 6000 jpegs on the issue,  then chrome will become very slow, sometimes no response at all.

while firefox is no problem...

**Comment by tofi86** [comment] 2015-10-19 12:14
I assume this is an issue with the FancyBox library we're using...
https://github.com/fancyapps/fancyBox/

Does this also happen when you download the FancyBox standalone package and replace their demo images with your large images?

**Comment by marilawang** [comment] 2015-10-20 05:59
well, it seems to be the thumbnail preview image problem, 
so I changed some code to avoid this problem.

I deleted this line:
```
<% if defined?(thumbnails) && thumbnails %>
```

and the else part in the view.

**Comment by tofi86** [comment] 2015-11-21 20:54
> can you explain the if condition? cuz I don't find any "thumbnails" variable...

thumbnails comes from the native redmine thumbnail functionality. This line is part of the original redmine view: http://www.redmine.org/projects/redmine/repository/entry/trunk/app/views/attachments/_links.html.erb
You shouldn't delete it!

**Comment by tofi86** [comment] 2015-11-21 20:54
Also, I can't reproduce the issue. Closing it for the moment. Feel free to reopen if needed.

**Closed by tofi86** 2015-11-21 20:54 UTC
