### ISSUE TITLE
Vertical scrolling broken in Chrome (redmine_lightbox2 v0.3.2)

### ISSUE THREAD

**Issue by gituser** [paginagmbh/redmine_lightbox2#37] opened 2017-04-18 14:36 UTC
Hi.

Using commit 2dd50dd4588a1c187e73e856100a61c50600e819 version `0.3.2` it breaks vertical scrolling in /issues/* in Chrome browser, in Firefox works fine, didn't test in other browsers.

Redmine is `v3.3.3`.

If I disable the plugin scroll works again.

Can you fix this?

Many thanks

**Comment by tofi86** [comment] 2017-04-18 14:49
What do you mean by "is broken"? When being in lightbox mode, vertical scrolling is disabled in all browsers. in Chrome and in Firefox and others...

**Comment by gituser** [comment] 2017-04-18 14:57
Here is how to reproduce:

go to any page which contains more content than can be displayed at once in your browser (e.g. http://www.redmine.org/issues or http://www.redmine.org/issues/25616).

Plugin hooks into /issues/ page and thus something does with the scroll in Chrome. In Firefox everything works just fine.

**Comment by tofi86** [comment] 2017-04-18 15:03
I'm afraid, but I cannot reproduce this. I'm running Redmine 3.3.3.stable.16539 with the default theme and a bunch of plugins, and also tried another theme, but I can't reproduce. Scroll is working fine, also for "long" issues...

Did you try using another theme?

Or disabling *all* plugins but the lightbox plugin?

I tested with Chrome 57.0.2987.133 and Firefox 52.0.2 on Windows 10.

**Comment by patprache** [comment] 2017-07-05 08:31
I have the same configuration and ... the same behavior with chrome 59, can you do something ?

**Comment by daltinn** [comment] 2017-07-14 12:45
I'm also have that problem with installed plugins agile

**Comment by asimko** [comment] 2017-07-20 09:10
The same problem here ...

**Comment by tofi86** [comment] 2017-07-24 21:28
I will try to have a look soon...

Did anybody also report this issue to the author of the redmine agile plugin?
If someone could do so, that would be great!

**Comment by tofi86** [comment] 2017-07-27 20:08
Confirmed. I can reproduce the issue. However, I cannot solve this by myself. I wrote an email to the redmine_agile developers as their plugin throws an exception in the chrome console which may be the root cause of the problem.

**Comment by tofi86** [comment] 2017-07-28 14:33
Still waiting for an answer of the redmine_agile developers.

In the meantime I pushed some fixes and changes for general Redmine 3.4 support (#38). Go check out the new `master` branch...

**Comment by tofi86** [comment] 2017-07-28 17:28
This is going to be fixed by the redmine_agile team. It's an issue with their CSS. So I'm closing this ticket here.

In the meantime, you can use the workaround provided by their team:

> Hello Tobias,
> 
> To fix the issue with the scrolling please do the next.
> 
> /assets/stylesheets/redmine_agile.css
> 
> ```
> html {
> -  overflow-y: inherit !important;
> +  /* overflow-y: inherit !important; */
> }
>```
> 
> Then restart your web-server.
> 
> And we will investigate the second issue also and surely fix it.
> 
> Regards, Irina

**Closed by tofi86** 2017-07-28 17:28 UTC
Labels: bug
