### ISSUE TITLE
error while login into redmine backend

### ISSUE THREAD

**Issue by tniebergall** [paginagmbh/redmine_lightbox2#14] opened 2015-09-22 10:38 UTC
Hi,

i've installed this extension with redmine version 3.1.0 and easy redmine.
After the installation process i get a error 500 and the following message in the production.log, when a user tries to login.

```
Started GET "/redmine/" for "Server-IP" at 2015-09-22 12:34:07 +0200
Processing by MyController#page as HTML
  Current user: "non-admin-user" (id=663)
Completed 500 Internal Server Error in 342ms (ActiveRecord: 16.3ms)

NoMethodError (undefined method `quoted_left_column_name' for #<Class:0x00000005088e00>):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by tofi86** [comment] 2015-09-22 12:15
This has nothing to do with the `redmine_lightbox` plugin, right?
Did you want to open an issue in the [redmine_sudo](https://github.com/tofi86/redmine_sudo) repository?

**Comment by tniebergall** [comment] 2015-09-22 12:20
This only happens with redmine_ligtbox2 installed.
When I remove it everything runs finde, so i thought it's an issue with this plugin.

redmine_sudo isn't installed on this system

**Comment by tofi86** [comment] 2015-09-22 12:40
Okay, thanks.

But unfortunately I cannot reproduce with original redmine 3.1.1
This is the log for a normal login and then going to m

```
Started GET "/" for SERVER_IP at 2015-09-22 14:29:43 +0200
Processing by WelcomeController#index as HTML
  Current user: anonymous
Redirected to HOSTNAMElogin?back_url=HOSTNAME
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 8ms (ActiveRecord: 1.1ms)
Started GET "/login?back_url=HOSTNAME" for SERVER_IP at 2015-09-22 14:29:43 +0200
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"HOSTNAME"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (12.2ms)
Completed 200 OK in 66ms (Views: 57.2ms | ActiveRecord: 3.0ms)
Started POST "/login" for SERVER_IP at 2015-09-22 14:29:53 +0200
Processing by AccountController#login as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"AUTH_TOKEN", "back_url"=>"HOSTNAME", "username"=>"ext_test", "password"=>"[FILTERED]", "login"=>"Anmelden »"}
  Current user: anonymous
Successful authentication for 'ext_test' from SERVER_IP at 2015-09-22 12:29:53 UTC
Redirected to HOSTNAME
Completed 302 Found in 17ms (ActiveRecord: 3.6ms)
Started GET "/" for SERVER_IP at 2015-09-22 14:29:53 +0200
Processing by WelcomeController#index as HTML
  Current user: ext_test (id=36)
  Rendered news/_news.html.erb (9.0ms)
  Rendered welcome/index.html.erb within layouts/base (33.8ms)
Completed 200 OK in 248ms (Views: 80.4ms | ActiveRecord: 8.3ms)
Started GET "/my/page" for SERVER_IP at 2015-09-22 14:30:01 +0200
Processing by MyController#page as HTML
  Current user: ext_test (id=36)
  Rendered my/blocks/_timelog.html.erb (19.5ms)
  Rendered issues/_list_simple.html.erb (12.6ms)
  Rendered my/blocks/_issueswatched.html.erb (30.8ms)
  Rendered issues/_list_simple.html.erb (2.6ms)
  Rendered my/blocks/_issuesassignedtome.html.erb (13.3ms)
  Rendered my/page.html.erb within layouts/base (68.6ms)
Completed 200 OK in 247ms (Views: 231.3ms | ActiveRecord: 5.1ms)
```

"My Page" loads perfectly well.

In fact, the lightbox plugin doesn't even load in the `MyController` class as you can see here:
https://github.com/paginagmbh/redmine_lightbox2/blob/master/lib/hooks/view_layouts_base_html_head_hook.rb

Probably easyRedmine is somehow patched and doesn't contain the original redmine core functions?

**Comment by tniebergall** [comment] 2015-09-22 12:45
Okay thank's for your time.

I'll contact easyRedmine to check it.

**Comment by tofi86** [comment] 2015-11-21 20:37
Closing this for the moment. Feel free to reopen if you're still having trouble with this...

**Closed by tofi86** 2015-11-21 20:37 UTC
